#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_1.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_2.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_3.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_4.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_5.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_6.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_7.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_8.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_9.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_10.h5
python python/add_nSubJettiness.py /data/LCD/V3/littleGammaPi0/Pi0Escan_0.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_0.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_1.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_2.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_3.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_4.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_5.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_6.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_7.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_8.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_9.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_10.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_11.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_12.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_13.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_14.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_15.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_16.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_17.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_18.h5
#python python/add_nSubJettiness.py /data/LCD/V3/littleData/Pi0/Pi0_19.h5
