#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_1.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_2.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_3.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_4.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_5.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_6.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_7.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_8.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_9.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Gamma/gamma_60_GeV_10.h5
python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_1.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_2.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_3.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_4.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_5.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_6.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_7.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_8.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_9.h5
#python python/add_nSubJettiness.py ../AllFiles/H5Files/v1/Skimmed_withNSub/Pi0/pi0_60_GeV_10.h5
