python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_0.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_1.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_2.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_3.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_4.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_5.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_6.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_7.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_8.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_9.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_10.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_11.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_12.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_13.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_14.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_15.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_16.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_17.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_18.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Pi0/Pi0Escan_19.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_0.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_1.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_2.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_3.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_4.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_5.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_6.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_7.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_8.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_9.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_10.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_11.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_12.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_13.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_14.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_15.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_16.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_17.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_18.h5
python python/axis_fix.py /data/LCD/V3/GammaPi0/Gamma/GammaEscan_19.h5
