python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_0.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_1.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_2.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_3.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_4.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_5.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_6.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_7.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_8.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_9.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_10.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_11.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_12.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_13.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_14.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_15.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_16.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_17.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_18.h5
python python/axis_fix.py /data/LCD/V3/littleData/Pi0/Pi0_19.h5
