python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_0.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_1.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_2.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_3.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_4.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_5.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_6.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_7.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_8.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_9.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_10.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_11.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_12.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_13.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_14.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_15.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_16.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_17.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_18.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Gamma/GammaEscan_19.h5 /data/LCD/V3/Downsampled/GammaPi0/Gamma/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_0.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_1.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_2.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_3.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_4.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_5.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_6.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_7.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_8.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_9.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_10.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_11.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_12.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_13.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_14.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_15.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_16.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_17.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_18.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/GammaPi0/Pi0/Pi0Escan_19.h5 /data/LCD/V3/Downsampled/GammaPi0/Pi0/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_0.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_1.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_2.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_3.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_4.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_5.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_6.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_7.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_8.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_9.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_10.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_11.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_12.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_13.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_14.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_15.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_16.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_17.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_18.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/Ele/EleEscan_19.h5 /data/LCD/V3/Downsampled/EleChPi/Ele/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_0.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_1.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_2.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_3.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_4.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_5.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_6.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_7.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_8.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_9.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_10.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_11.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_12.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_13.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_14.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_15.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_16.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_17.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_18.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
python downsample.py /data/LCD/V3/Original/EleChPi/ChPi/ChPiEscan_19.h5 /data/LCD/V3/Downsampled/EleChPi/ChPi/ 5
